### ISSUE TITLE
Let users set the name of the output files

### ISSUE THREAD

**Issue by jlustigy** [dflemin3/approxposterior#36]
Currently `chainFile` does this for the MCMC chains, but it would be nice to make this an attribute of `approxposterior.approx.ApproxPosterior` for all associated outputs.

**Comment by dflemin3** [comment]
Good catch! I removed the parameter `chainFile` and replaced it with `runName` where `runName` is the generic prefix for all cached files, i.e. those written when `cache == True`.  The change is on the dev branch and will be migrated to master shortly.
