### ISSUE TITLE
Use latin hypercube sampler to initialize GP optimizations

### ISSUE THREAD

**Issue by jlustigy** [dflemin3/approxposterior#46]
This could help to ensure that the global minimum is actually found, and that any potential local minima are included in the cross-validation calculation (see #41).

**Comment by dflemin3** [comment]
Added GP hyperpriors and dramatically improved GP hyperparameter optimization in #55 and earlier commits. With these changes, maximizing the GP marginal likelihood seems to work well in general for `approxposterior`'s use cases.
